name: Unit Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v3.0.1
      - name: Setup the environment
        run: rye sync --all-features
      - name: Run tests
        run: rye run pytest --cov=./ --cov-branch --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v4.5.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
